# Generated by Django 4.1.1 on 2022-10-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='swift',
            new_name='code',
        ),
    ]
